/* tslint:disable */
/* eslint-disable */
/**
 * Products API
 * Basic products API service ;)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {Product}
     * @memberof CreateProductRequest
     */
    product: any;
}
