/* tslint:disable */
/* eslint-disable */
/**
 * Products API
 * Basic products API service ;)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    ID?: any;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    size: any;
}
